export const ROUTES = {
  ceoDashboard: "/ceo/dashboard",
  ceoClasses: "/ceo/classes",
  ceoChats: "/ceo/chats",
  ceoRoomMembers: "/ceo/rooms/members",
  ceoAssignTeachers: "/ceo/assign-teachers",
  ceoAssignParents: "/ceo/assign-parents",
  ceoUsers: "/ceo/users",
  directorDashboard: "/director/dashboard",
  teacherDashboard: "/teacher/dashboard",
  parentDashboard: "/parent/dashboard",
  classes: "/classes",
  parents: "/parents",
  teachers: "/teachers",
  directors: "/directors",
  chats: "/chats",
  contacts: "/contacts",
  privateChatsNew: "/private-chats/new",
  settings: "/settings",
  login: "/login",
  signup: "/signup",
  roles: "/roles",
  demoChecklist: "/demo-checklist",
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
